CREATE DATABASE QLKS
GO

USE QLKS
GO



CREATE TABLE CHUCVU
(
	MACV INT IDENTITY(1,1) PRIMARY KEY,
	TENCHUCVU NVARCHAR(20) CHECK (TENCHUCVU  NOT LIKE '%[^A-Za-z0-9 ]%') 
)

CREATE TABLE TAIKHOAN
(
	TAIKHOAN NVARCHAR(30) CHECK(LEN(TAIKHOAN) >= 0) UNIQUE,
	MATKHAU NVARCHAR(30)  CHECK(LEN(MATKHAU) >= 0) NOT NULL,
	CHUCVU INT CONSTRAINT FK_CHUCVU FOREIGN KEY (CHUCVU) REFERENCES CHUCVU(MACV) ON DELETE SET NULL
)


CREATE TABLE KHACHHANG
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY,
	TENKH NVARCHAR(30) CHECK(TENKH NOT LIKE '%[^A-Za-z ]%') NOT NULL,
	CCCD VARCHAR(12) CHECK(CCCD NOT LIKE '%[^0-9]%' AND LEN(CCCD) = 12) UNIQUE NOT NULL,
	SDT VARCHAR(10) CHECK(SDT NOT LIKE '%[^0-9]%' AND LEN(SDT) = 10) NULL,
	DIACHI NVARCHAR(30) CHECK(DIACHI NOT LIKE '%[^A-Za-z0-9 ]%')NULL,
	GIOITINH NVARCHAR(3) CHECK(GIOITINH IN ('Nam','Nữ')) NOT NULL DEFAULT 'Nam'
)
GO

CREATE TABLE LOAINHANVIEN
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(20) CHECK (TENLOAI NOT LIKE '%[^A-Za-z0-9 ]%') 
)
CREATE TABLE NHANVIEN
(
	MANV INT IDENTITY(1,1) PRIMARY KEY,
	TENNV NVARCHAR(30) CHECK(TENNV NOT LIKE '%[^A-Za-z ]%') NOT NULL,
	SDT VARCHAR(10) CHECK(SDT NOT LIKE '%[^0-9]%' AND LEN(SDT) = 10) NULL,
	DIACHI NVARCHAR(30) CHECK(DIACHI NOT LIKE '%[^A-Za-z0-9] %') NULL,
	GIOITINH NVARCHAR(3) CHECK(GIOITINH IN ('Nam','Nữ')) NOT NULL,
	LOAINV INT CONSTRAINT FK_LOAINV FOREIGN KEY (LOAINV) REFERENCES LOAINHANVIEN(MALOAI) ON DELETE SET NULL
)
GO

CREATE TABLE TINHTRANGPHONG
(
	MATINHTRANG INT IDENTITY(1,1) PRIMARY KEY,
	TENTINHTRANG NVARCHAR(30) CHECK (TENTINHTRANG LIKE '%[A-Za-z0-9 ]%') 
)

GO

CREATE TABLE LOAIPHONG
(
	MALOAIPHONG NVARCHAR(3)  PRIMARY KEY ,
	TENLOAIPHONG NVARCHAR(20),
	SoNguoiToiDa int check(songuoitoida > 0)
) 
GO

CREATE TABLE PHONG
(
	MAPHONG INT IDENTITY(1,1) PRIMARY KEY,
	TENPHONG NVARCHAR(4) CHECK(TENPHONG LIKE 'A[0-9][0-9][0-9]') NOT NULL,
	LOAIPHG NVARCHAR(3) CONSTRAINT PK_LoaiPhg FOREIGN KEY (LOAIPHG) REFERENCES LOAIPHONG(MALOAIPHONG) ON DELETE SET NULL,
	DONGIA MONEY CHECK(DONGIA > 0) NOT NULL,
	TINHTRANG INT CONSTRAINT PK_TINHTRANG FOREIGN KEY (TINHTRANG) REFERENCES TINHTRANGPHONG(MATINHTRANG) ON DELETE SET NULL DEFAULT 1,
)
GO

CREATE TABLE LOAIDICHVU
(
	MALOAIDV INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(30) CHECK (TENLOAI NOT LIKE '%[^A-Za-z0-9 ]%') 
)

GO

CREATE TABLE DICHVU
(
	MADV INT IDENTITY(1,1) PRIMARY KEY,
	TENDV NVARCHAR(30) CHECK (TENDV NOT LIKE '%[^A-Za-z0-9 ]%') NOT NULL UNIQUE,
	LOAI INT CONSTRAINT PK_LOAIDV FOREIGN KEY (LOAI) REFERENCES LOAIDICHVU(MALOAIDV) ON DELETE SET NULL,
	DONGIA MONEY CHECK(DONGIA > 0) NOT NULL,
)	
GO

CREATE TABLE PHIEUDATPHONG
(
	MADATPHG INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MAKH INT CONSTRAINT PK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE SET NULL
)
GO

CREATE TABLE CHITIETPHIEUDATPHONG
(
	MADATPHG INT NOT NULL,
	MAPHG INT NOT NULL, 
	NGAYDAT DATE,
	NGAYNHAN DATE
)
GO

ALTER TABLE CHITIETPHIEUDATPHONG ADD CONSTRAINT PK_CHITIETPHIEUDATPHONG PRIMARY KEY(MADATPHG,MAPHG)
ALTER TABLE CHITIETPHIEUDATPHONG ADD CONSTRAINT FK_MADATPHG FOREIGN KEY (MADATPHG) REFERENCES PHIEUDATPHONG(MADATPHG) ON DELETE CASCADE
ALTER TABLE CHITIETPHIEUDATPHONG ADD CONSTRAINT FK_MAPHG FOREIGN KEY (MAPHG) REFERENCES PHONG(MAPHONG ) ON DELETE CASCADE

GO


CREATE TABLE PHIEUNHANPHONG
(
	MANHANPHG INT IDENTITY(1,1) PRIMARY KEY ,
	MADATPHG INT CONSTRAINT PK_PHIEUNHANPHONG_MADATPHG FOREIGN KEY (MADATPHG) REFERENCES PHIEUDATPHONG(MADATPHG) ON DELETE CASCADE,
	MAKH INT CONSTRAINT PK_PHIEUNHANPHONG_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE SET NULL
)
GO

CREATE TABLE CHITIETPHIEUDNHANPHONG
(
	MANHANPHG INT NOT NULL,
	MADATPHG INT NOT NULL,
	MAKH INT NOT NULL,
	NGAYNHAN DATE,
	NGAYTRADUKIEN DATE,
	NGAYTRATHUCTE DATE, 
)
GO

ALTER TABLE CHITIETPHIEUDNHANPHONG ADD CONSTRAINT PK_CHITIETPHIEUDNHANPHONG PRIMARY KEY(MANHANPHG,MADATPHG,MAKH)
ALTER TABLE CHITIETPHIEUDNHANPHONG ADD CONSTRAINT FK_CHITIETPHIEUDNHANPHONG_MADATPHG FOREIGN KEY (MADATPHG) REFERENCES PHIEUDATPHONG(MADATPHG) ON DELETE NO ACTION
ALTER TABLE CHITIETPHIEUDNHANPHONG ADD CONSTRAINT FK_CHITIETPHIEUDNHANPHONG_MANHANPHG FOREIGN KEY (MANHANPHG) REFERENCES PHIEUNHANPHONG(MANHANPHG) ON DELETE CASCADE
ALTER TABLE CHITIETPHIEUDNHANPHONG ADD CONSTRAINT FK_CHITIETPHIEUDNHANPHONG_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE NO ACTION

GO

CREATE TABLE SUDUNGDICHVU
(
	MASUDUNGDV INT IDENTITY (1,1) PRIMARY KEY,
	MADV INT CONSTRAINT FK_SUDUNGDICHVU_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV) ON DELETE SET NULL,
	MANHANPHG INT CONSTRAINT FK_MANHANPHG FOREIGN KEY (MANHANPHG) REFERENCES PHIEUNHANPHONG(MANHANPHG) ON DELETE CASCADE,
	SOLUONG INT CHECK(SOLUONG >= 0)
)

GO

CREATE TABLE HOADON
(
	MAHD INT IDENTITY(1,1)PRIMARY KEY NOT NULL,
	MANV INT CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE SET NULL ,
	MAKH INT CONSTRAINT FK_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE SET NULL,
	MANHANPHG INT CONSTRAINT FK_HOADON_MANHANPHG FOREIGN KEY (MANHANPHG) REFERENCES PHIEUNHANPHONG(MANHANPHG) ON DELETE CASCADE,
	TONGTIEN MONEY CHECK (TONGTIEN > 0),
	NGAYLAP DATE,
)
GO

CREATE TABLE CHITIETHOADON
(
	MAHOADON INT NOT NULL CONSTRAINT FK_MAHOADON2 FOREIGN KEY (MAHOADON) REFERENCES HOADON(MAHD)  ON DELETE CASCADE ,
	MAPHG INT NOT NULL CONSTRAINT FK_MAPHG2 FOREIGN KEY (MAPHG) REFERENCES PHONG(MAPHONG)  ON DELETE NO ACTION,
	MASUDUNGDV INT NOT NULL CONSTRAINT FK_MASUDUNGDV2 FOREIGN KEY (MASUDUNGDV) REFERENCES SUDUNGDICHVU(MASUDUNGDV)  ON DELETE NO ACTION,
	PHUTHU MONEY CHECK(PHUTHU >= 0),
	TIENPHG MONEY,
	TIENDV MONEY,
	SONGAY INT CHECK(SONGAY >= 0),
	THANHTIEN MONEY
)
GO

ALTER TABLE CHITIETHOADON ADD CONSTRAINT PK_CHITIETHOADON2 PRIMARY KEY(MAHOADON,MAPHG ,MASUDUNGDV)

